# Generated by Django 3.1.12 on 2021-12-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration',
            field=models.IntegerField(default=2017331104),
            preserve_default=False,
        ),
    ]
