# Generated by Django 3.1.12 on 2021-12-12 07:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Doctor's Name")),
                ('content', models.CharField(max_length=100, verbose_name='Specialty')),
                ('chamber', models.CharField(max_length=200, verbose_name="Chamber's Name")),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('fees', models.IntegerField(default=0)),
                ('start_time', models.TimeField(verbose_name='Chamber Beginning Time')),
                ('end_time', models.TimeField(verbose_name='Chamber Ending Time')),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(verbose_name='Behavior')),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
    ]
