# Generated by Django 3.1.12 on 2021-12-13 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500, verbose_name='Contact Email')),
                ('personal_website', models.CharField(blank=True, max_length=500, verbose_name='Personal Website')),
                ('m_uni', models.CharField(blank=True, max_length=400, verbose_name="Master's University")),
                ('phd_uni', models.CharField(blank=True, max_length=400, verbose_name='PhD University')),
                ('current_employer', models.CharField(blank=True, max_length=500, verbose_name='Current Employer')),
                ('position', models.CharField(blank=True, max_length=500, verbose_name='Position')),
                ('github', models.CharField(blank=True, max_length=500, verbose_name='Github')),
                ('linkedin', models.CharField(blank=True, max_length=500, verbose_name='LinkedIn')),
                ('research_area', models.CharField(blank=True, max_length=500, verbose_name='Research Area')),
                ('work_field', models.CharField(blank=True, max_length=500, verbose_name='Working Field')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
    ]
