# Generated by Django 3.1.12 on 2021-12-12 11:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211212_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '  Monday'), (1, '  Tuesday'), (2, '  Wednesday'), (3, '  Thursday'), (4, '  Friday'), (5, '  Saturday'), (6, '  Sunday')], default=1, max_length=13, verbose_name='Available Days'),
            preserve_default=False,
        ),
    ]
