# Generated by Django 3.1.12 on 2021-12-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
    ]
